# Generated by Django 2.1 on 2020-04-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
    ]
